# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fde96adcaf2c13502fccecb60952126608c61c8bf3683fca2f62842aaa57020e21ec2c109ed002e833d51c7a212ddac6f16f88591f1fe263d2288ffeae63e9ce

test:
  secret_key_base: 33c4a4b7275cdc21e1f96562d3f54e843857916ab3f8ae58c195b2194057e5fbdd7db13b7e347de33288d3552c7816fbd32bfa56b82a342033ece186565918de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
